config/routes.rb
Rails.application.routes.draw do
  
  get 'posts/new'

  root 'posts#index'

  resources :users
  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/new_post', to:'posts#new'
  post '/new_post', to:'posts#create'
  #get '/posts', to:'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts

  attr_accessor :remember_token
  
  #2 fonctions utilisées par la méthode remember
  class << self
    #Create a digest based on a string
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end



  def remember
    #Créer un remember_token
    self.remember_token = User.new_token
    #Met le digest de ce token dans la base de donnée
    update_attribute( :remember_digest, User.digest(@remember_token) )  
  end

  def forget
     update_attribute( :remember_digest, nil )  
  end

  #Method to identify wether the user is the right one (the digest of the input remember_token == remember_digest)
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.author = current_user.name
    if @post.save
      flash[:success] = "the post was successfully submitted !"
      redirect_to root_path
    else
      flash[:danger] = "the post wasn't submitted"
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private

    def post_params
        params.require(:post).permit(:content)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    #Find user
    user = User.find_by(email:params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      #if remember me is coché launch remember otherwise launch forget
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to current_user
    else
      flash.now[:danger] = "Invalid username / password"
      render :new
    end

  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id] #Si on a une session on fait comme avant
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:id] #Sinon si on a un cookie permanent
      user = User.find_by(id: cookies.signed[:id]) #on essaie de retrouver l'user qui correspond
      if user && user.authenticated?(cookies[:remember_token]) #si on l'a trouvé (user non nul) et le digest du cookie remember_token est le même que son remember_digest
        log_in(user) 
        @current_user = user
      end
    end
  end

  def remember(user)
    #use the User method remember
    user.remember
    #create the 2 cookies one for id and one with the remember_token
    cookies.permanent[:remember_token] = user.remember_token
    cookies.permanent.signed[:id] = user.id
  end

  def forget(user)
    #use the User method forget
    user.forget
    #delete the 2 cookies
    cookies.delete(:id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <p><%= link_to "Home", root_path %></p>
  
    <% if logged_in? %>
      <p><%= link_to "Index of users", users_path %></p>
      <p><%= link_to "Your profile", current_user %></p>
      <p><%= link_to "Log out", logout_path, method: :delete %></p>
      <p><%= link_to "New Post", new_post_path %></p>
    <% else %>
      <p><%= link_to "Log In", login_path %></p>
    <% end %>
      
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
        <div class="alert_message"><%= message %></div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>List of posts by members</h1>

<ul>
<% @posts.each do |post|%>
  <li>
    <%= post.content %>
    <br>
    <% if logged_in? %>
    by <em><%= post.author %></em>
    <% end %>
  </li>
<%end%>
</ul>

app/views/posts/new.html.erb
<h1>This is the page to make a post</h1>

<%= form_for(:post, url: new_post_path) do |f| %>

  <p>
    <%= f.label :content %>
    <%= f.text_field :content, size: 120 %>
  </p>

  <p>
    <%= f.submit "Post !" %>
  </p>

<% end %>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<p>This is the home page of my app !</p>

app/views/users/index.html.erb
<h1>List of recorded users</h1>

<p>
<% @users.each do |user| %>
  <ul>
    <li><%= user.name %>, <%= user.email %></li>
  </ul>
<% end %>
</p>

app/views/users/show.html.erb
<h1>User page</h1>

<p>User name: <%= @user.name %></p>
<p>User email: <%= @user.email %></p>